# Generated by Django 5.0 on 2023-12-24 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_investmentoffercomment'),
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentoffer',
            name='funding_round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='startup.fundinground'),
            preserve_default=False,
        ),
    ]
