# Generated by Django 4.2.7 on 2023-12-24 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=2048)),
                ('startup_avatar', models.ImageField(default='iamges/default.jpg', upload_to='images/')),
                ('startup_sector', models.CharField(choices=[('Energy', 'Energy'), ('Healthcare', 'Healthcare'), ('Real Estate', 'Real Estate'), ('Pharma & Biotech', 'Pharma & Biotech'), ('Chemicals', 'Chemicals'), ('Environment Services', 'Environment Services'), ('Industrial & Manufacturing', 'Industrial & Manufacturing'), ('Agriculture & Food Processing', 'Agriculture & Food Processing'), ('Financial Services', 'Financial Services'), ('Transport & Logistics', 'Transport & Logistics'), ('Mining & Metals', 'Mining & Metals'), ('Tourism & Quality of Life', 'Tourism & Quality Of Life'), ('Information & Communication Technology', 'Information & Communication Technology'), ('Human Capital Innovation', 'Human Capital Innovation'), ('Aerospace & Defense', 'Aerospace & Defense')], max_length=1024)),
                ('startup_websits', models.TextField()),
                ('startup_email', models.CharField(max_length=2048)),
                ('startup_number', models.CharField(max_length=1024)),
                ('startup_description', models.TextField()),
                ('startup_founder_name', models.CharField(max_length=1024)),
                ('startup_target_market', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=1024)),
                ('team_avatar', models.ImageField(default='iamges/default.jpg', upload_to='images/')),
                ('team_role', models.CharField(max_length=2048)),
                ('team_linkdin', models.TextField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.startup')),
            ],
        ),
        migrations.CreateModel(
            name='FundingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_percentage', models.FloatField()),
                ('fund_amount', models.IntegerField()),
                ('fund_status', models.CharField(choices=[('Close', 'Close'), ('Open', 'Open')], max_length=1024)),
                ('fund_current_close', models.FloatField()),
                ('fund_stage', models.CharField(choices=[('Pre_Seed', 'Pre Seed'), ('Seed', 'Seed'), ('Series A', 'Series A'), ('Series B', 'Series B'), ('Series C', 'Series C'), ('Series D', 'Series D'), ('Mezzanine', 'Mezzanine'), ('IPO', 'Ipo')], max_length=1024)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.startup')),
            ],
        ),
    ]
