# Generated by Django 4.2.7 on 2023-12-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundinground',
            name='fund_current_close',
        ),
        migrations.AlterField(
            model_name='fundinground',
            name='fund_status',
            field=models.CharField(choices=[('Close', 'Close'), ('Open', 'Open')], default='Open', max_length=1024),
        ),
    ]
