# Generated by Django 5.0 on 2023-12-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorprofile',
            name='inverstor_avatar',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
