# Generated by Django 5.0 on 2024-01-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_investorprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorprofile',
            name='invested_campany',
        ),
    ]
